# Generated by Django 6.0.5 on 2026-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
